### ISSUE TITLE
mastic: Change agg_param format to support fast-start and/or simultaneous level computation?

### ISSUE THREAD

**Issue by hannahedavis** [jimouris/draft-mouris-cfrg-mastic#24]
In a comment, @cjpatton raised the idea of a "fast-start" mode that allows aggregators to begin aggregating at an arbitrary level with an arbitrary set of starting prefixes. Currently Mastic does not support this feature because the FLP must be verified at level zero before any further output can be validated. Since aggregators do not necessarily store information about previous rounds except when validating aggregation parameters, one suggestion was to change the aggregation parameter to include information about which level was first evaluated. The downside of this is that the aggregation parameter format would become inconsistent with Poplar, and thus introduce changes at the DAP level. 

Another suggestion, with the same downside, is to change the aggregation parameter format to a tuple of the current aggregation parameter types. Mastic could then support simultaneous aggregation of multiple different levels on the same reports. The validity condition on the new aggregation parameters would be the existing condition applied to the parameters' union. 

The one solution that doesn't require aggregation parameters to change is to fix the starting level as a parameter of the VDAF scheme.

**Comment by hannahdaviscrypto** [comment]
Fast-start added to Mastic. The aggregation parameter now includes a boolean flag indicating whether the FLP should be verified, and a sequence of aggregation parameters ins considered only if one of them includes an FLP verification.
