### ISSUE TITLE
Describing Other Aggregatable Functions in more details

### ISSUE THREAD

**Issue by pratiksarkar93** [jimouris/draft-mouris-cfrg-mastic#39]
I think we should explicitly mention (in Section 5.2 or Section 5.4?) how we can perform functions like Variance and Standard Deviation as it involves changing the beta value in a non-trivial way. 
beta = (x, x^2) and the FLP needs to prove that the relation holds.

**Comment by jimouris** [comment]
I like this idea, it'd make Section 5 more readable by adding concrete examples like this. Can you lead this one? I can also help.

**Comment by pratiksarkar93** [comment]
Sure I can do that.

**Comment by cjpatton** [comment]
We list some things you can do in the intro. Beyond this I don't think we need any more non-normative language on this. Once we're ready, we'll specify concrete variants of Mastic, something like this section for Prio3:
https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf#section-7.4
