### ISSUE TITLE
Fiat-Shamir vulnerability due to binding to wrong inputs

### ISSUE THREAD

**Issue by divergentdave** [jimouris/draft-mouris-cfrg-mastic#48]
Currently, joint randomness parts depend on each VIDPF key. This is insufficient, because it admits the following attack: An adversarial client generates VIDPF keys honestly for some input alpha, but then throws away the "w" part of the correction words in the public share. They can now compute the joint randomness parts, joint randomness seed, and joint randomness field elements, because they only depend on the blinds, VIDPF keys, and nonce (all chosen randomly by honest clients). Next, the dishonest client uses foreknowledge of the joint randomness values to select one of many FLP measurements that result in cancellation during the random linear combination part of the validity circuit. For example, if the circuit is Sum(8), I think they could fix the first seven measurement elements to be, say -1, and then solve to find what value of the eighth measurement element would result in a circuit output of zero. Treating the circuit as a univariate function of the eighth measurement element, it is a quadratic polynomial, known to the attacker, so they should have two zeros to choose from. Now, the attacker can program this adversarially-chosen measurement into the VIDPF by re-running VIDPF key generation, reusing the same initial seeds and alpha. Only the "w" parts of the correction words will change. The resulting report would pass one-hotness checks and path checks, because the core seeds/control bits of the VIDPF evaluation were not tampered with. The aggregators would extract the late-programmed adversarial measurement from their collective calls to `VIDPF.eval()` with each key and inputs `0b0` and `0b1`, and it would pass FLP verification by construction.

The straightforward fix for this is to compute `beta_share` for each aggregator, as in `Vidpf.eval()`, and replace `vidpf_init_seed[0]`/`vidpf_init_seed[1]` in joint randomness part derivation with each `beta_share`. That way, we would bind joint randomness to the FLP measurement, by binding to both measurement shares. (A less complicated but less efficient option would be to include shares of beta directly in each input share, and use those in both joint randomness derivation and FLP verification, rather than extracting shares of beta from evaluations at `0b0` and `0b1`, as is done currently.)

**Comment by cjpatton** [comment]
Quite a coincidence: we were just discussing this possibility today! Thanks for giving a concrete attack.

We thinking of adding the VIDPF public share (including the correction words) to the binder. This was at least sufficient for Doplar (ia.cr/2023/130, Theorem 3); we suspect it's also sufficient here, but still need to do the proof.

Adding `beta_share` to the binder would likely also work. I'll leave it to @hannahdaviscrypto to close this issue.
