### ISSUE TITLE
Add draft versioning

### ISSUE THREAD

**Issue by cjpatton** [jimouris/draft-mouris-cfrg-mastic#71]
We're currently use `VERSION` from draft-irtf-cfrg-vdaf for domain separation. Eventually we'll need to control versioning here so that we can break compatibility across drafts.

**Comment by jimouris** [comment]
Is this just a matter of adding a constant on the code that indicates which draft version this is or something else?

**Comment by cjpatton** [comment]
Yes, as well as replacing calls to `format_dst()` with our own thing.
